# graphql/typedefs.gql

type Query {
  posts: [Post]
  post(id: ID!): Post
  tags: [Tag]
  tag(name: String!): Tag
  user(id: ID, username: String): User
}

type Mutation {
  createAccessToken(username: String!, password: String!): accessToken
  signup(username: String!, password: String!): User
  createPost(data: CreatePostInput!): Post
}

input CreatePostInput {
  title: String!
  content: String!
}

type accessToken {
  token: String
}

# Post's description can go here
type Post {
  _id: ID
  # title of post
  title: String
  content: String
  tags: [Tag]
  author: User
  comments: [Comment]
}

type Comment {
  _id: ID
  content: String
  author: User
}

type User {
  _id: ID
  username: String
  posts: [Post]
}

# Since tag has no unique ID, it's hard to cache on client
type Tag {
  name: String
  posts: [Post]
}
